add envs

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -1,82 +1,69 @@
 name: Deploy Next.js site
 on:
-    push:
-        branches: ["master"]
-    workflow_dispatch:
+  push:
+    branches: ["master"]
+  workflow_dispatch:
 
 permissions:
-    contents: read
-    pages: write
-    id-token: write
+  contents: read
+  pages: write
+  id-token: write
 
 concurrency:
-    group: "nextdeploy"
-    cancel-in-progress: false
+  group: "nextdeploy"
+  cancel-in-progress: false
 
 jobs:
-    build:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout
-              uses: actions/checkout@v4
-            - name: Detect package manager
-              working-directory: ./
-              id: detect-package-manager
-              run: |
-                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-                    echo "manager=yarn" >> $GITHUB_OUTPUT
-                    echo "command=install" >> $GITHUB_OUTPUT
-                    echo "runner=yarn" >> $GITHUB_OUTPUT
-                    exit 0
-                  else
-                    echo "Unable to determine package manager"
-                    exit 1
-                  fi
-            - name: Setup Node
-              uses: actions/setup-node@v4
-              with:
-                  node-version: "20.10.0"
-                  cache: ${{ steps.detect-package-manager.outputs.manager }}
-                  cache-dependency-path: |
-                      ${{ github.workspace }}/yarn.lock
-            - name: Restore cache
-              uses: actions/cache@v3
-              with:
-                  path: |
-                      .next/cache
-                  # Generate a new cache whenever packages or source files change.
-                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-                  # If source files changed but packages didn't, rebuild from a prior cache.
-                  restore-keys: |
-                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
-            - name: Install dependencies
-              working-directory: ./
-              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-            - name: Build with Next.js
-              working-directory: ./
-              run: ${{ steps.detect-package-manager.outputs.runner }} build
-            - name: Add static JS scripts etc to the standalone app. In future consider uploading the static files to a CDN.
-              working-directory: ./
-              run: ${{ steps.detect-package-manager.outputs.runner }} add-static
-            - name: Upload artifact
-              uses: actions/upload-pages-artifact@v3
-              with:
-                  name: family-tree
-                  path: ./.next/standalone
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Detect package manager
+        working-directory: ./
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "23.6.0"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          cache-dependency-path: |
+            ${{ github.workspace }}/yarn.lock
+      - name: Install dependencies
+        working-directory: ./
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js
+        working-directory: ./
+        run: ${{ steps.detect-package-manager.outputs.runner }} build
+      - name: Add static JS scripts etc to the standalone app. In future consider uploading the static files to a CDN.
+        working-directory: ./
+        run: ${{ steps.detect-package-manager.outputs.runner }} add-static
 
-    # Deployment job
-    deploy:
-        runs-on: self-hosted
-        needs: build
-        steps:
-            - name: Download artifact
-              uses: actions/download-artifact@v4
-              with:
-                  name: family-tree
-                  path: ./
-            - name: Extract artifact and restart the app
-              run: |
-                  echo "moving the artifact";
-                  tar -xf artifact.tar -C /home/ubuntu/services/family-tree;
-                  rm artifact.tar;
-                  pm2 restart "Family Tree" && pm2 reset "Family Tree"
+      - name: Upload to server
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          port: ${{ secrets.SSH_PORT }}
+          key: ${{ secrets.SSH_KEY }}
+          source: ./.next/standalone
+          target: ${{ vars.SSH_DIST_DEST }}
+
+  # Deployment job
+  deploy:
+    runs-on: self-hosted
+    needs: build
+    steps:
+      - name: Restart app
+        run: |
+          PB_API_LOGIN="${{ secrets.PB_API_LOGIN }}" PB_API_PASSWORD="${{ secrets.PB_API_PASSWORD }}" PB_URL="${{ secrets.PB_URL }}" SSR_POCKETBASE_URL="${{ secrets.SSR_POCKETBASE_URL }}" PORT="${{ vars.PORT }}" pm2 restart "Family Tree" --update-env && pm2 reset "Family Tree"
